# ==================================
#  YAPIMARU_Plugin Configuration
# ==================================

# /hub ã‚³ãƒãƒ³ãƒ‰ã®ãƒ†ãƒ¬ãƒãƒ¼ãƒˆå…ˆåº§æ¨™
hub-location:
  world: 'hub'
  x: 336.50
  y: 192.00
  z: -94.50
  yaw: 0.00
  pitch: 0.00

# ==================================
#  Whitelist (ãƒ›ãƒ¯ã‚¤ãƒˆãƒªã‚¹ãƒˆ) æ©Ÿèƒ½
# ==================================
# ã“ã®ã‚»ã‚¯ã‚·ãƒ§ãƒ³ã¯ãƒ—ãƒ©ã‚°ã‚¤ãƒ³ã«ã‚ˆã£ã¦ç®¡ç†ã•ã‚Œã¾ã™ã€‚
# ã‚ªãƒ¼ãƒŠãƒ¼(operators)ãƒªã‚¹ãƒˆã®ã¿æ‰‹å‹•ã§ç·¨é›†å¯èƒ½ã§ã™ã€‚
whitelist:
  mode: OFF
  owners:
    - "002c8ff8-fbdb-4752-b166-fe609ee031b4"
  candidates: []
  allowed: []


# ==================================
#  FakeName (å½å) æ©Ÿèƒ½
# ==================================
# ãƒ—ãƒ¬ã‚¤ãƒ¤ãƒ¼ã®å½åè¨­å®šã¯ã“ã®ä¸‹ã«è‡ªå‹•çš„ã«ä¿å­˜ã•ã‚Œã¾ã™ã€‚
players:
  a72adb64-acef-49ab-a8e8-d6bb424aff54:
    base_name: KURU
    linked_name: 'KURU'
  458574b6-4951-4d0e-a6d1-52709771be9b:
    base_name: YAPIMARU
    linked_name: 'YAPIMARU'
  00000000-0000-0000-0009-01fc1e3647f8:
    base_name: YAPIMARU
    linked_name: 'YAPIMARU'
  305672f0-da6b-4c79-b4d6-64a6d676c639:
    base_name: ã¿ãã‚
    linked_name: 'ã¿ãã‚'
  00000000-0000-0000-0009-01f86b2feb79:
    base_name: ã¿ãã‚
    linked_name: 'ã¿ãã‚'
  dbde0329-e5b9-417b-8163-30ecaed0468f:
    base_name: ã¿ã‚ã‹
    linked_name: 'ã¿ã‚ã‹'
  00000000-0000-0000-0009-01f0138a4ea5:
    base_name: ãªã‚Šãˆã 
    linked_name: 'ï¼˜ãƒ“ãƒƒãƒˆ'
  00000000-0000-0000-0009-01ffbbd91f10:
    base_name: ã®!ã‚€
    linked_name: 'Emz'
  61a550eb-6069-49b9-81a1-73abd0e61749:
    base_name: ã—ã‚‰
    linked_name: 'MAX'
  57d6e5f5-cf96-4267-8c4d-345b6c0961b9:
    base_name: äº”è‡“å…­è…‘
    linked_name: 'R-T'
  7971ec94-c2ac-4d82-b30f-d127cb2ac476:
    base_name: ã‚¢ãƒƒã‚·ãƒ¥
    linked_name: 'ã‚¢ãƒƒã‚·ãƒ¥'
  00000000-0000-0000-0009-01f3796420bb:
    base_name: Shigure Lunar
    linked_name: 'ã‚¢ãƒ³ã‚¸ã‚§ãƒ­'
  00000000-0000-0000-0009-01fbec7f563c:
    base_name: ã¿ã©ã´ãƒ¼
    linked_name: 'ã‚¢ãƒ³ãƒãƒ¼'
  00000000-0000-0000-0009-01f6ba32b1fc:
    base_name: ãˆã´ã¾ã‚ˆ
    linked_name: 'ã‚¤ãƒ´'
  00000000-0000-0000-0009-01f43d9eb313:
    base_name: ç™¾ç€¬ã‚¤ãƒã‚¸ãƒãƒ¼ã‚·ãƒ§ãƒ³
    linked_name: 'ã‚¦ã‚£ãƒ­ãƒ¼'
  00000000-0000-0000-0009-01f254c8f7ce:
    base_name: ã´ãƒ¼ã¾ã™
    linked_name: 'ã‚¨ãƒ‰ã‚¬ãƒ¼'
  9759c876-df95-426b-abdc-5aa551090f51:
    base_name: ã¡ã‚“
    linked_name: 'ã‚¨ãƒªã‚¶ãƒ™ã‚¹'
  00000000-0000-0000-0009-01f9cd332e50:
    base_name: ã‚¿ãƒ«ãƒ³
    linked_name: 'ã‚¨ãƒ«ãƒ»ãƒ—ãƒªãƒ¢'
  00000000-0000-0000-0009-01fc87e2e213:
    base_name: Leia
    linked_name: 'ã‚ªãƒ¼ãƒ†ã‚£ã‚¹'
  ceb27c38-6210-403d-af31-bd602e1917b8:
    base_name: ã›ãª
    linked_name: 'ã‚ªãƒ¼ãƒªãƒ¼'
  00000000-0000-0000-0009-01f0606160a1:
    base_name: ã›ãª
    linked_name: 'ã‚ªãƒ¼ãƒªãƒ¼'
  00000000-0000-0000-0009-01fd47a7b1c2:
    base_name: ã‚‚ã¯ãŠ
    linked_name: 'ã‚¬ã‚¹'
  f6fb5723-7807-4d1d-accc-0ab601632a73:
    base_name: Dã®æ„æ€
    linked_name: 'ã‚«ã‚¼'
  00000000-0000-0000-0009-01f3bbee6b8b:
    base_name: Dã®æ„æ€
    linked_name: 'ã‚«ã‚¼'
  fdc5a128-b431-4225-a631-cc037bdc8c61:
    base_name: ã‚‚ãã–ã„ğŸªµ
    linked_name: 'ã‚­ãƒƒãƒˆ'
  e566a109-8004-4ad4-9c9b-1891cdf88a94:
    base_name: ã„ãªã“ã“
    linked_name: 'ã‚¯ãƒ©ãƒ³ã‚·ãƒ¼'
  00000000-0000-0000-0009-01f772df6f87:
    base_name: ãˆã
    linked_name: 'ã‚°ãƒªãƒ•'
  00000000-0000-0000-0009-01f2a19dc479:
    base_name: ã¿ã‚“ã¡ã‚ƒ
    linked_name: 'ã‚°ãƒ¬ã‚¤'
  00000000-0000-0000-0009-01fd4482d154:
    base_name: ã´ãƒ¼ãµã‚†
    linked_name: 'ã‚¯ãƒ­ã‚¦'
  00000000-0000-0000-0009-01fb76c0c510:
    base_name: ãã¿
    linked_name: 'ã‚°ãƒ­ãƒ '
  4cc215e2-172d-48b0-8bd6-493eaee9fb61:
    base_name: halhal
    linked_name: 'ã‚²ã‚¤ãƒ«'
  00000000-0000-0000-0009-01f26d0a440b:
    base_name: halhal
    linked_name: 'ã‚²ã‚¤ãƒ«'
  00000000-0000-0000-0009-01fc6965a24e:
    base_name: GA
    linked_name: 'ã‚±ãƒ³ã‚¸'
  49a8a2dd-87c8-4f3b-96ac-57e8129e1a95:
    base_name: ãã†
    linked_name: 'ã‚³ãƒ¼ãƒ‡ãƒªã‚¢ã‚¹'
  25df0d97-abb8-4218-8f49-7a7b315c9229:
    base_name: Kinora
    linked_name: 'ã‚³ãƒ«ãƒˆ'
  00000000-0000-0000-0009-01f2b7986943:
    base_name: åµãƒãƒ³
    linked_name: 'ã‚³ãƒ¬ãƒƒãƒˆ'
  00000000-0000-0000-0009-01f32f87532d:
    base_name: ã•ã˜ãªã’
    linked_name: 'ã‚µãƒ¼ã‚¸'
  1ebbc065-96ff-4575-b6f5-0a9b39fe0f43:
    base_name: ã‚ã‚Šã¾ã«
    linked_name: 'ã‚µãƒ '
  36ce0385-95fa-4b4b-83c2-f70d278cb6ba:
    base_name: IBO
    linked_name: 'ã‚µãƒ³ãƒ‡ã‚£'
  00000000-0000-0000-0009-01f46a9ba84d:
    base_name: syou
    linked_name: 'ã‚·ã‚§ã‚¤ãƒ‰'
  b563d3f3-ba75-41f8-b0dc-29f1dd92d31f:
    base_name: ãªã‚ˆ
    linked_name: 'ã‚¸ã‚§ã‚·ãƒ¼'
  00000000-0000-0000-0009-01f7a0bdac8d:
    base_name: Nemesis
    linked_name: 'ã‚¸ã‚§ãƒ¨ãƒ³'
  f2c8796b-4662-471a-b296-cfbddd55f1f9:
    base_name: ã‚†ã…ã¹ã
    linked_name: 'ã‚·ã‚§ãƒªãƒ¼'
  00000000-0000-0000-0009-01f15b8efcc4:
    base_name: ã‚†ã…ã¹ã
    linked_name: 'ã‚·ã‚§ãƒªãƒ¼'
  a0c2f4f7-9b14-4c69-b5f9-3dc2d41b8678:
    base_name: ã¾ã
    linked_name: 'ã‚¸ãƒ£ãƒƒã‚­ãƒ¼'
  00000000-0000-0000-0009-01fd6c662f2f:
    base_name: ã¾ã
    linked_name: 'ã‚¸ãƒ£ãƒƒã‚­ãƒ¼'
  f18e3d63-4533-49ca-9909-a75f44ea63ab:
    base_name: ãã†ãã‚“
    linked_name: 'ã‚¸ãƒ£ãƒãƒƒãƒˆ'
  00000000-0000-0000-0009-01f13397c389:
    base_name: Kaspe
    linked_name: 'ã‚¸ãƒ¥ã‚¸ãƒ¥'
  2fcbd892-a516-45e1-9506-79657c50c0fd:
    base_name: ã®ãƒ¼ã‚€
    linked_name: 'ã‚¹ã‚¯ã‚¦ã‚£ãƒ¼ã‚¯'
  ab4a15c7-df17-4e34-a63b-07679d88825e:
    base_name: ã®ã‚‹ãŒã¶
    linked_name: 'ã‚¹ãƒˆã‚¥ãƒ¼'
  00000000-0000-0000-0009-01f241aeece9:
    base_name: ã®ã‚‹ãŒã¶
    linked_name: 'ã‚¹ãƒˆã‚¥ãƒ¼'
  00000000-0000-0000-0009-01f58105f73f:
    base_name: ã¿ã‚“ã¡ã‚ƒJr
    linked_name: 'ã‚¹ãƒ‘ã‚¤ã‚¯'
  00000000-0000-0000-0009-01f7b52367ae:
    base_name: è±†ã¡ã‚ƒã‚“ã¾ã‚“
    linked_name: 'ã‚¹ãƒ—ãƒ©ã‚¦ãƒˆ'
  1506c1fa-e173-4fc4-b749-a36867f93fb2:
    base_name: Taku
    linked_name: 'ãƒ€ã‚¤ãƒŠãƒã‚¤ã‚¯'
  00000000-0000-0000-0009-01f6a010220f:
    base_name: Taku
    linked_name: 'ãƒ€ã‚¤ãƒŠãƒã‚¤ã‚¯'
  9e86123c-8c27-4e2d-a521-794d0b538c53:
    base_name: ã‚†ãƒ¼ã¡ãƒ
    linked_name: 'ãƒ€ã‚°'
  00000000-0000-0000-0009-01fe1b071026:
    base_name: ã‚ˆãª
    linked_name: 'ã‚¿ãƒ©'
  00000000-0000-0000-0009-01fc750db849:
    base_name: ã‚‚ãã«ãƒ
    linked_name: 'ãƒ€ãƒªãƒ«'
  00000000-0000-0000-0009-01fdfa4f0824:
    base_name: ã´ã„ã–
    linked_name: 'ãƒã‚§ã‚¹ã‚¿ãƒ¼'
  cce46048-7470-45ac-9343-eea95e146c7a:
    base_name: ãƒãƒƒã‚­ãƒ¼
    linked_name: 'ãƒãƒ£ãƒ¼ãƒªãƒ¼'
  00000000-0000-0000-0009-01f542d6329b:
    base_name: ãƒãƒƒã‚­ãƒ¼
    linked_name: 'ãƒãƒ£ãƒ¼ãƒªãƒ¼'
  00000000-0000-0000-0009-01fb4a64478f:
    base_name: tatu
    linked_name: 'ãƒãƒ£ãƒƒã‚¯'
  5653cfd9-6274-4464-aec5-6edff2a85ff8:
    base_name: mizukiti
    linked_name: 'ãƒ†ã‚£ãƒƒã‚¯'
  00000000-0000-0000-0009-01f5adf8e52b:
    base_name: mizukiti
    linked_name: 'ãƒ†ã‚£ãƒƒã‚¯'
  72b12686-a6a0-4daf-9186-5a90a8b9db86:
    base_name: AKAKISUSHI
    linked_name: 'ãƒ‰ãƒ©ã‚³'
  98e76d4f-7957-4c46-ba07-40d39391ab34:
    base_name: å¤§å·¥
    linked_name: 'ãƒŠãƒ¼ãƒ‹'
  300c0991-7c40-4b9f-8932-eda1162286c1:
    base_name: ãã‚‰ã‚ã‘
    linked_name: 'ãƒ‹ã‚¿'
  78f0a95c-afb4-4488-803b-97e335b8c39b:
    base_name: ã†ãã…
    linked_name: 'ãƒãƒ¼ãƒªãƒ¼'
  00000000-0000-0000-0009-01f8fbad4d99:
    base_name: ã‚‚ã‚ã„
    linked_name: 'ãƒ‘ãƒ¼ãƒ«'
  323de687-fd91-4251-b410-ad312916fd91:
    base_name: Tiger
    linked_name: 'ãƒã‚¤ãƒ­ãƒ³'
  00000000-0000-0000-0009-01f7a04a96fe:
    base_name: Tiger
    linked_name: 'ãƒã‚¤ãƒ­ãƒ³'
  00000000-0000-0000-0009-01f5b1963363:
    base_name: ã‚Šãƒ¼ã¡
    linked_name: 'ãƒã‚º'
  00000000-0000-0000-0009-01f2aadb02e2:
    base_name: ã‚ãƒ¼ã‚‹
    linked_name: 'ãƒã‚¹ã‚¿ãƒ¼'
  00000000-0000-0000-0009-01fc744763d7:
    base_name: ã‚‰ã¦
    linked_name: 'ãƒ‘ãƒ '
  00000000-0000-0000-0009-01f47dc8e9b5:
    base_name: tosi
    linked_name: 'ãƒãƒ³ã‚¯'
  70bc0910-bfed-4aa9-b1cf-add835c9f2f6:
    base_name: shonbo
    linked_name: 'ãƒ“ãƒ¼'
  00000000-0000-0000-0009-01f8ca4c186f:
    base_name: å››è‘‰ã®ãã¾ã¡ã‚ƒã‚“ã±ã‚“ã¤
    linked_name: 'ãƒ“ãƒ“'
  00000000-0000-0000-0009-01f144e7ee47:
    base_name: ã¡ã„ã‹ã‚
    linked_name: 'ãƒ•ã‚¡ãƒ³ã‚°'
  002c8ff8-fbdb-4752-b166-fe609ee031b4:
    base_name: ã¿ã‹
    linked_name: 'ãƒ•ã‚£ãƒ³ã‚¯ã‚¹'
  53d9b80a-1f20-4efc-8ddb-166c49e23f6b:
    base_name: ã‚ãã­
    linked_name: 'ãƒ•ãƒ©ãƒ³ã‚±ãƒ³'
  00000000-0000-0000-0009-01fe91c20733:
    base_name: ã‚ãã­
    linked_name: 'ãƒ•ãƒ©ãƒ³ã‚±ãƒ³'
  00000000-0000-0000-0009-01f5d5a41f25:
    base_name: ã²ã•ã½ã‚“
    linked_name: 'ãƒ–ãƒ«'
  aed99939-43fe-4f4a-919c-aafa23d8bd18:
    base_name: 'â‚á¢â€¥á¢â‚ '
    linked_name: 'ãƒ–ãƒ­ãƒƒã‚¯'
  4b5d81c6-7c93-41e9-97bf-3ed825b1d8f0:
    base_name: ã¾ã‹ã‚ã«
    linked_name: 'ãƒšãƒ‹ãƒ¼'
  00000000-0000-0000-0009-01fa1bf2e275:
    base_name: ã¾ã‹ã‚ã«
    linked_name: 'ãƒšãƒ‹ãƒ¼'
  00000000-0000-0000-0009-01f432136c28:
    base_name: ã‚¶ãƒ©ã‚·
    linked_name: 'ãƒ™ãƒªãƒ¼'
  00000000-0000-0000-0009-01f0bffa128b:
    base_name: é›·é›·é›·
    linked_name: 'ãƒ™ãƒ«'
  46ec5e53-d8b3-4f67-b93f-2eb6976329ac:
    base_name: ã‚„ã‚‹æ°—ã¾ã‚“ã¾ã‚“ä¸¸
    linked_name: 'ãƒœã‚¦'
  00000000-0000-0000-0009-01fa5d909ed8:
    base_name: ã‚„ã‚‹æ°—ã¾ã‚“ã¾ã‚“ä¸¸
    linked_name: 'ãƒœã‚¦'
  00000000-0000-0000-0009-01f0ef81fdc7:
    base_name: ã²ã‚
    linked_name: 'ãƒã‚³'
  00000000-0000-0000-0009-01fcc0a4fa6d:
    base_name: ãŠãŸã„
    linked_name: 'ãƒœãƒ‹ãƒ¼'
  00000000-0000-0000-0009-01f46bea9e19:
    base_name: ã‚ˆ
    linked_name: 'ãƒãƒ³ãƒ‡ã‚£'
  00000000-0000-0000-0009-01f6d6dca770:
    base_name: ã—ã‚“
    linked_name: 'ãƒŸãƒ¼ãƒ—ãƒ«'
  00000000-0000-0000-0009-01fcfce095cf:
    base_name: ã—ã‚“ã˜ã‚“
    linked_name: 'ãƒŸã‚³'
  00000000-0000-0000-0009-01f8c7be29d8:
    base_name: ã“ã‚‹ã¶ã‚‹
    linked_name: 'ãƒŸã‚¹ã‚¿ãƒ¼P'
  00000000-0000-0000-0009-01fca4c5c231:
    base_name: ãƒ‰ãƒ¼ãƒŠãƒ„
    linked_name: 'ãƒ¡ã‚¤ã‚¸ãƒ¼'
  00000000-0000-0000-0009-01f7971089a6:
    base_name: èµ¤æ°´
    linked_name: 'ãƒ¡ã‚°'
  1e70cf8c-a154-4a47-b90b-743c6ccd916e:
    base_name: ã‚„ã¾ã‚†ã†
    linked_name: 'ãƒ¡ãƒ­ãƒ‡ã‚£ãƒ¼'
  f87d5f94-54ef-44fe-a2b9-a71a43c28680:
    base_name: N.s0807
    linked_name: 'ãƒ¢ãƒ¼'
  00000000-0000-0000-0009-01fbd0d4983e:
    base_name: N.s0807
    linked_name: 'ãƒ¢ãƒ¼'
  c0f88948-3f95-4c2d-8d9e-ce2da783153a:
    base_name: OwG
    linked_name: 'ãƒ¢ãƒ¼ãƒ†ã‚£ã‚¹'
  00000000-0000-0000-0009-01f31556c6fc:
    base_name: OwG
    linked_name: 'ãƒ¢ãƒ¼ãƒ†ã‚£ã‚¹'
  3e7919d4-adb9-4ae0-ada5-031147c11623:
    base_name: ã ãƒ¼ã™
    linked_name: 'ãƒ©ãƒ•ã‚¹'
  00000000-0000-0000-0009-01ffe6350060:
    base_name: ãƒˆãƒŸãƒ¼Jr
    linked_name: 'ãƒ©ãƒªãƒ¼'
  2a966d90-244d-4ae3-a541-2cdb5498ba47:
    base_name: ã‚¹ãƒ‘ãƒŠ
    linked_name: 'ãƒªã‚³'
  b0a585ee-cc9f-4fe1-8e58-96b3796c7c06:
    base_name: ã—ã’ã‚‹
    linked_name: 'ãƒªãƒªãƒ¼'
  00000000-0000-0000-0009-01f35c34a1ae:
    base_name: ã‚Šã‹
    linked_name: 'ãƒ«ãƒ¼'
  00000000-0000-0000-0009-01fb09e403f5:
    base_name: IGUTYAN
    linked_name: 'ãƒ«ãƒŸ'
  f7f189d3-b65f-4876-9ec2-8377860f5d68:
    base_name: ã¶ã©ã†
    linked_name: 'ãƒ¬ã‚ªãƒ³'
  00000000-0000-0000-0009-01f544928627:
    base_name: ã¶ã©ã†
    linked_name: 'ãƒ¬ã‚ªãƒ³'
  fb790cc7-fc16-4471-b5b6-909ce6af951e:
    base_name: Mira
    linked_name: 'ãƒ­ãƒ¼ã‚µ'
  89083010-d104-4f0d-b969-9040264545e1:
    base_name: Sora
    linked_name: 'ãƒ­ãƒ¼ãƒ©'
  00000000-0000-0000-0009-01fe6e5c117e:
    base_name: Sora
    linked_name: 'ãƒ­ãƒ¼ãƒ©'
  00000000-0000-0000-0009-01f6b6b85408:
    base_name: ãƒˆãƒŸãƒ¼
    linked_name: 'ãƒ­ãƒ¼ãƒªãƒ¼'
  690d5928-d1d9-4098-a768-e6b8fb92e9d6:
    base_name: ã¿ã‹
    linked_name: 'ç®¡ç†äºº'
  00000000-0000-0000-0009-01f8e1f83f1a:
    base_name: ã¿ã‹
    linked_name: 'ãƒ•ã‚£ãƒ³ã‚¯ã‚¹'